name: CloudCart CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: cloudcart
  EKS_CLUSTER: cloudcart-eks

jobs:
  deploy:
    name: Build, Push and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::185529490140:role/cloudcart-github-actions-role
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push backend image
        run: |
          docker build -t ${{ env.ECR_REPOSITORY }}:backend-${{ github.sha }} ./backend
          docker tag ${{ env.ECR_REPOSITORY }}:backend-${{ github.sha }} 185529490140.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:backend-${{ github.sha }}
          docker push 185529490140.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:backend-${{ github.sha }}

      - name: Build and push frontend image
        run: |
          docker build -t ${{ env.ECR_REPOSITORY }}:frontend-${{ github.sha }} ./frontend
          docker tag ${{ env.ECR_REPOSITORY }}:frontend-${{ github.sha }} 185529490140.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:frontend-${{ github.sha }}
          docker push 185529490140.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:frontend-${{ github.sha }}

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER }}

      - name: Deploy backend to EKS
        run: |
          kubectl -n default set image deployment/cloudcart-backend \
            backend=185529490140.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:backend-${{ github.sha }}

      - name: Deploy frontend to EKS
        run: |
          kubectl -n default set image deployment/cloudcart-frontend \
            frontend=185529490140.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:frontend-${{ github.sha }}

      - name: Wait for deployments
        run: |
          kubectl -n default rollout status deployment/cloudcart-backend --timeout=180s
          kubectl -n default rollout status deployment/cloudcart-frontend --timeout=180s
